// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database as CoreDatabase } from './types';

type SignupRpcDatabase = {
  public: {
    Functions: {
      accept_client_invitation_signup: {
        Args: { p_token: string; p_user_id: string };
        Returns: string;
      };
      accept_employee_invitation_signup: {
        Args: { p_employee_id?: string | null; p_token: string; p_user_id: string };
        Returns: string;
      };
      claim_pending_invitations: { Args: never; Returns: number };
      create_client_signup_membership: {
        Args: { p_organization_id: string; p_user_id: string };
        Returns: string;
      };
      find_signup_organization: {
        Args: { p_slug_or_code: string };
        Returns: {
          id: string;
          name: string;
          org_code: string;
          slug: string;
        }[];
      };
      get_client_invitation_details: {
        Args: { p_token: string };
        Returns: {
          expires_at: string;
          id: string;
          invited_email: string;
          organization_code: string | null;
          organization_id: string;
          organization_name: string | null;
          status: "pending" | "accepted" | "expired" | "cancelled" | "rejected";
        }[];
      };
      get_employee_invitation_details: {
        Args: { p_token: string };
        Returns: {
          employee_role_id: string | null;
          expires_at: string;
          id: string;
          invited_email: string;
          organization_code: string | null;
          organization_id: string;
          organization_name: string | null;
          role: "admin" | "manager" | "employee";
          status: "pending" | "accepted" | "expired" | "cancelled" | "rejected";
        }[];
      };
      search_signup_organizations: {
        Args: { p_limit?: number; p_query: string };
        Returns: {
          id: string;
          name: string;
          org_code: string;
          slug: string;
        }[];
      };
    };
  };
};

type Database = CoreDatabase & SignupRpcDatabase;

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing required environment variables: VITE_SUPABASE_URL and/or VITE_SUPABASE_PUBLISHABLE_KEY. ' +
    'Please check your .env file.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/core/api/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
