// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database as CoreDatabase } from './types';

type SignupRpcDatabase = {
  public: {
    Functions: {
      claim_pending_invitations: { Args: never; Returns: number };
      find_signup_organization: {
        Args: { p_slug_or_code: string };
        Returns: {
          id: string;
          name: string;
          org_code: string;
          slug: string;
        }[];
      };
      search_signup_organizations: {
        Args: { p_limit?: number; p_query: string };
        Returns: {
          id: string;
          name: string;
          org_code: string;
          slug: string;
        }[];
      };
    };
  };
};

type Database = CoreDatabase & SignupRpcDatabase;

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing required environment variables: VITE_SUPABASE_URL and/or VITE_SUPABASE_PUBLISHABLE_KEY. ' +
    'Please check your .env file.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/core/api/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
