import {
  AlertTriangle,
  ArrowDownCircle,
  ArrowUpCircle,
  Box,
  Briefcase,
  Building,
  Calendar,
  CheckCircle,
  Clock3,
  CreditCard,
  DollarSign,
  FileCheck,
  FileText,
  Layers,
  Phone,
  Share2,
  ShoppingCart,
  Truck,
  UserPlus,
  Wrench,
  X,
} from "lucide-react";
import type { NotificationType } from "@/core/types/notifications";

export const NOTIFICATION_ICONS: Record<NotificationType, JSX.Element> = {
  contract_signed: <FileCheck className="h-4 w-4 text-success" />,
  contract_expiring: <AlertTriangle className="h-4 w-4 text-warning" />,
  quote_accepted: <CheckCircle className="h-4 w-4 text-success" />,
  quote_rejected: <X className="h-4 w-4 text-destructive" />,
  document_shared: <Share2 className="h-4 w-4 text-info" />,
  esignature_requested: <FileText className="h-4 w-4 text-primary" />,
  esignature_completed: <CheckCircle className="h-4 w-4 text-success" />,
  plan_limit_warning: <AlertTriangle className="h-4 w-4 text-warning" />,
  plan_limit_reached: <AlertTriangle className="h-4 w-4 text-destructive" />,
  purchase_order_approved: <ShoppingCart className="h-4 w-4 text-success" />,
  member_joined: <UserPlus className="h-4 w-4 text-primary" />,
  lead_created: <Briefcase className="h-4 w-4 text-primary" />,
  account_created: <Building className="h-4 w-4 text-primary" />,
  contact_created: <Phone className="h-4 w-4 text-primary" />,
  activity_created: <Calendar className="h-4 w-4 text-primary" />,
  supplier_created: <Truck className="h-4 w-4 text-primary" />,
  inventory_item_created: <Box className="h-4 w-4 text-primary" />,
  purchase_order_created: <ShoppingCart className="h-4 w-4 text-primary" />,
  production_order_created: <Wrench className="h-4 w-4 text-primary" />,
  financial_record_created: <DollarSign className="h-4 w-4 text-success" />,
  document_template_created: <Layers className="h-4 w-4 text-primary" />,
  auto_document_created: <FileText className="h-4 w-4 text-primary" />,
  document_version_created: <FileCheck className="h-4 w-4 text-primary" />,
  subscription_created: <CheckCircle className="h-4 w-4 text-success" />,
  subscription_cancelled: <AlertTriangle className="h-4 w-4 text-warning" />,
  plan_upgraded: <ArrowUpCircle className="h-4 w-4 text-success" />,
  plan_downgraded: <ArrowDownCircle className="h-4 w-4 text-warning" />,
  payment_success: <CreditCard className="h-4 w-4 text-success" />,
  payment_failed: <CreditCard className="h-4 w-4 text-destructive" />,
  trial_started: <Clock3 className="h-4 w-4 text-info" />,
  trial_ended: <Clock3 className="h-4 w-4 text-warning" />,
};
